import { pgTable, serial, text, timestamp, date, integer } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const applicationsTable = pgTable("applications", {
  id: serial("id").primaryKey(),
  refNumber: text("ref_number").notNull().unique(),

  // Step 1: Learner
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  middleName: text("middle_name"),
  preferredName: text("preferred_name"),
  idNumber: text("id_number").notNull(),
  birthCertNumber: text("birth_cert_number"),
  dob: date("dob").notNull(),
  age: integer("age"),
  gender: text("gender").notNull(),
  nationality: text("nationality").notNull(),
  citizenship: text("citizenship"),
  countryOfBirth: text("country_of_birth"),
  homeLanguage: text("home_language").notNull(),
  secondLanguage: text("second_language"),
  learningLanguage: text("learning_language"),
  religion: text("religion"),
  mobileNumber: text("mobile_number"),
  email: text("email"),
  residentialAddress: text("residential_address").notNull(),
  city: text("city").notNull(),
  province: text("province").notNull(),
  postalCode: text("postal_code"),
  country: text("country").notNull(),
  livesWith: text("lives_with"),
  totalSiblings: integer("total_siblings"),
  familyPosition: text("family_position"),
  siblingsAtSchool: text("siblings_at_school"),

  // Step 2: Academic
  preferredStartYear: integer("preferred_start_year"),
  gradePassed: text("grade_passed"),
  yearPassedHighest: integer("year_passed_highest"),
  currentGrade: text("current_grade"),
  currentAcademicYear: integer("current_academic_year"),
  prevSchoolName: text("prev_school_name").notNull(),
  prevSchoolAddress: text("prev_school_address"),
  prevSchoolPhone: text("prev_school_phone"),
  reasonLeaving: text("reason_leaving"),
  averagePercentage: text("average_percentage"),
  bestSubject: text("best_subject"),
  weakestSubject: text("weakest_subject"),
  numSubjectsPassed: integer("num_subjects_passed"),
  gradeApplying: text("grade_applying").notNull(),
  chosenStream: text("chosen_stream"),
  optionalSubject: text("optional_subject"),
  needsSupport: text("needs_support"),
  needsExtraLessons: text("needs_extra_lessons"),
  achievements: text("achievements"),
  sportsParticipation: text("sports_participation"),
  leadershipRoles: text("leadership_roles"),
  extracurricular: text("extracurricular"),
  hasDisciplineHistory: text("has_discipline_history"),
  disciplineDetails: text("discipline_details"),
  motivationToJoin: text("motivation_to_join").notNull(),
  referralSource: text("referral_source").notNull(),
  hasTeacherRelative: text("has_teacher_relative"),
  teacherName: text("teacher_name"),
  teacherSurname: text("teacher_surname"),
  teacherPhone: text("teacher_phone"),
  teacherRelationship: text("teacher_relationship"),

  // Step 3: Medical
  hasMedicalAid: text("has_medical_aid"),
  medAidProvider: text("med_aid_provider"),
  medAidNumber: text("med_aid_number"),
  hasFamilyDoctor: text("has_family_doctor"),
  doctorName: text("doctor_name"),
  doctorPhone: text("doctor_phone"),
  emergencyName: text("emergency_name").notNull(),
  emergencyPhone: text("emergency_phone").notNull(),
  emergencyRelationship: text("emergency_relationship"),
  medicalAllergies: text("medical_allergies"),
  medicalConditions: text("medical_conditions"),
  currentMedication: text("current_medication"),
  medAsthma: text("med_asthma"),
  medEpilepsy: text("med_epilepsy"),
  medDiabetes: text("med_diabetes"),
  hasDisability: text("has_disability"),
  disabilityDetails: text("disability_details"),
  needsCounselling: text("needs_counselling"),
  sportsAllowed: text("sports_allowed"),
  allowEmergencyTreatment: text("allow_emergency_treatment"),

  // Step 4: Parent/Guardian
  guardianFirstName: text("guardian_first_name").notNull(),
  guardianLastName: text("guardian_last_name").notNull(),
  guardianId: text("guardian_id").notNull(),
  guardianRelationship: text("guardian_relationship").notNull(),
  guardianMaritalStatus: text("guardian_marital_status"),
  guardianPhone: text("guardian_phone").notNull(),
  guardianAltPhone: text("guardian_alt_phone"),
  guardianWhatsapp: text("guardian_whatsapp"),
  guardianEmail: text("guardian_email"),
  guardianEmploymentStatus: text("guardian_employment_status"),
  guardianOccupation: text("guardian_occupation"),
  guardianEmployer: text("guardian_employer"),
  guardianIncomeRange: text("guardian_income_range"),
  guardianHomeAddress: text("guardian_home_address"),
  preferredCommunication: text("preferred_communication"),
  hasSecondGuardian: text("has_second_guardian"),
  guardian2Name: text("guardian2_name"),
  guardian2Phone: text("guardian2_phone"),
  permissionPhotos: text("permission_photos"),

  // Step 5: Declaration
  confirmTruth: text("confirm_truth").notNull(),
  agreePolicies: text("agree_policies").notNull(),
  digitalSignature: text("digital_signature").notNull(),
  submissionDate: date("submission_date").notNull(),
  additionalNotes: text("additional_notes"),

  // System
  status: text("status").notNull().default("pending"),
  submittedAt: timestamp("submitted_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertApplicationSchema = createInsertSchema(applicationsTable).omit({
  id: true,
  refNumber: true,
  status: true,
  submittedAt: true,
  updatedAt: true,
});

export type InsertApplication = z.infer<typeof insertApplicationSchema>;
export type Application = typeof applicationsTable.$inferSelect;
